version: '3.6'

services:

  db:
    image: registry.gitlab.com/dimalat/e-comm-rtu/db
    environment:
      POSTGRES_PASSWORD: qwerty
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8081:8080
