version: '3.6'

services:

  db:
    build:
      context: .
    image: e-comm-db
    environment:
      POSTGRES_PASSWORD: ${dbpass}
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8081:8080
